image: node:latest

stages:
  - build
  - test

# cache:
#   paths:
#     - node_modules/

build_bridge_evm:
  stage: build
  script:
  - cd ./bridges/evm
  - yarn
  cache:
    key: build-bridge-evm-cache
    paths:
    - ./bridges/evm/node_modules

test_bridge_evm:
  stage: test
  script: 
  - cd ./bridges/evm
  - yarn truffle test
  cache:
    key: build-bridge-evm-cache
