image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - cd bridges/evm && yarn
  # artifacts:
  #   paths:
  #     - node_modules/

testing_testing:
  stage: test
  script: cd bridges/evm && yarn truffle test
