image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build_bridge_evm:
  stage: build
  script:
    - cd ./bridges/evm && pwd && yarn
  # artifacts:
  #   paths:
  #     - node_modules/

test_bridge_evm:
  stage: test
  script: cd ./bridges/evm && pwd && yarn truffle test
