FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3-pip python3-dev

RUN pip3 install --upgrade pip
RUN pip3 install requests==2.24.0
RUN pip3 install cryptography==2.9.2
RUN pip3 install ccxt==1.30.77
