
data_source_info = [
    ("CoinGecko Cryptocurrency Price",
     "Retrieves current price of a cryptocurrency from https://www.coingecko.com"),
    ("CryptoCompare Cryptocurrency Price",
     "Retrieves current price of a cryptocurrency from https://www.cryptocompare.com"),
    ("Binance Cryptocurrency Price",
     "Retrieves current price of a cryptocurrency from https://www.binance.com/en"),
    ("Open Weather Map Weather Data",
     "Retrieves current weather information from https://www.openweathermap.org"),
    ("FreeForexAPI Gold Price",
     "Retrives current gold price from https://www.freeforexapi.com"),
    ("Alpha Vantage Stock Price",
     "Retrives current price of a stock from https://www.alphavaage.co"),
    ("Blockchain.info Bitcoin Block Count",
     "Retrives latest Bitcoin block height from https://www.blockchain.info"),
    ("BlockCypher Bitcoin Block Hash",
     "Retrives Bitcoin block hash at a given block height from https://blockcypher.com"),
    ("CoinGecko Cryptocurrency Trading Volume",
     "Retrieves current trading volume of a cryptocurrency from https://www.coingecko.com"),
    ("CryptoCompare Cryptocurrency Trading Volume",
     "Retrieves current trading volume of a cryptocurrency from https://www.cryptocompare.com"),
    ("ETH Gas Station Current Ethereum Gas Price",
     "Retrieves current Ethereum gas price from https://ethgasstation.info"),
    ("Open Sky Network Flight Data",
     "Retrieves flight information from https://opensky-network.org"),
    ("Quantum Random Number Generator",
     "Retrieves array of random number from https://qrng.anu.edu.au"),
    ("Yahoo Finance Stock Price",
     "Retrieves current price of a stock from https://finance.yahoo.com"),
]
