oracle_scripts_info = [
    ("Cryptocurrency Price in USD",
     "Oracle script that queries the average cryptocurrency price using current price data from CoinGecko, CryptoCompare, and Binance"),
    ("Gold Price in ATOMs",
     "Oracle script that queries current average gold price in ATOMs using gold price data from FreeForexAPI and ATOM price from Binance"),
    ("Stock Price (Alpha Vantage)",
     "Oracle script that queries the current price of a stock from Alpha Vantage"),
    ("Latest Bitcoin Block Count",
     "Oracle script that queries the latest Bitcoin block height from Blockchain.info"),
    ("Bitcoin Block Hash",
     "Oracle script for getting the Bitcoin block hash at the given block height""Oracle script that queries the Bitcoin block hash at the given block height from BlockCypher"),
    ("CoinGecko Cryptocurrency Volume",
     "Oracle script that queries a cryptocurrency's average trading volume for the past day from Coingecko"),
    ("CryptoCompare Cryptocurrency Volume",
     "Oracle script that queries a cryptocurrency's average trading volume for the past day from CryptoCompare"),
    ("Ethereum Gas Price",
     "Oracle script that queries the current Ethereum gas price from ETH gas station"),
    ("Open Sky Network",
     "Oracle script for checking whether a given flight number exists during the given time period from OpenSky Network"),
    ("Open Weather Map",
     "Oracle script that queries the current weather data of a location from OpenWeatherMap"),
    ("Quantum Random Number Generator",
     "Oracle script that queries a large random number from  Australia's National University Quantum Random API."),
    ("Yahoo Stock Price",
     "Oracle script that queries the current price of a stock from Yahoo Finance"),
    ("Fair Cryptocurrency Market Price",
     "Oracle script that queries the current price of a cryptocurrency from CoinGecko, CryptoCompare, and Binance and aggregates them using the user-selected method in the selected  base currency"),
]
