image: node:latest

cache:
  paths:
    - ./bridges/evm/node_modules/

bridge-evm-build:
  stage: build
  script:
  - cd ./bridges/evm
  - yarn

bridge-evm-test:
  stage: test
  script: 
  - cd ./bridges/evm
  - yarn truffle test
