name: Append Changelog
on: push

jobs:
  get-pr-name:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Get pull request info
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update CHANGELOG.md
        run: python3 .github/workflows/changelog.py
        if: success() && steps.findPr.outputs.body && steps.findPr.outputs.number
        env:
          PR_NUMBER: "${{ steps.findPr.outputs.number }}"
          PR_BODY: "${{ steps.findPr.outputs.body }}"

      - name: Get current Git branch
        run: export BRANCH=$(git rev-parse --abbrev-ref HEAD)
      
      - name: Stage changed files
        run: git add .
      
      - name: Commit changed files
        run: git commit -m "Auto-updating CHANGELOG.md"

      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH
