name: Append Changelog
on: push

jobs:
  get-pr-name:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Get pull request info
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update CHANGELOG.md
        run: python3 .github/workflows/changelog.py
        if: success() && steps.findPr.outputs.body && steps.findPr.outputs.number
        env:
          PR_NUMBER: "${{ steps.findPr.outputs.number }}"
          PR_BODY: "${{ steps.findPr.outputs.body }}"
      
      - name: Switching Git remote from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}

      - name: Get current Git branch
        run: export BRANCH=$(git rev-parse --abbrev-ref HEAD)
      
      - name: Stage changed files
        run: git add .
      
      - name: Commit changed files
        run: git commit -m "Auto-updating CHANGELOG.md"

      - name: Fetch from master
        run: git fetch origin $BRANCH

      - name: Push code to master
        run: git push -u origin $BRANCH
